<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/rs.co.amarinkovic.modules.IAMModule?artifactURI=file:/C:/Users/amarinkovic.S4HC/workspace/am_modules/Artifacts/Modules/rs.co.amarinkovic.modules.iammodule.module" categoryId="com.emc.ide.artifact.moduledef">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="io.amarinkovic.dctm.modules.IDummyModule" a_module_type="[Standard Module]">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <interfaceJars href="urn:com.emc.ide.artifact.jardef.jardef/am_modules-api?artifactURI=file:/C:/binaries/composer/workspace_aramco/dm_bof_module/Artifacts/JAR%20Definitions/am_modules-api.jardef#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/am_modules?artifactURI=file:/C:/Users/amarinkovic.S4HC/workspace/am_modules/Artifacts/JAR%20Definitions/am_modules.jardef#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="io.amarinkovic.dctm.modules.DummyModule"/>
    <miscellaneous objectName="Miscellaneous">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
